package org.exoplatform.context.listener;

import org.exoplatform.document.service.AccountService;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.context.ApplicationListener;
import org.springframework.context.event.ContextStartedEvent;

/**
 * For listening to events that are published a class needs o implement the ApplicationListener interface.
 * The above class listens for all events generated by the ApplicationContext.
 * 
 * @author <a href="mailto:sondn@exoplatform.com">Ngoc Son Dang</a>
 * @version ContextStartedEventListener.java Dec 31, 2013
 *
 */
public class ContextStartedEventListener implements ApplicationListener<ContextStartedEvent> {

    private static final Logger logger = LoggerFactory.getLogger(ContextStartedEventListener.class);
    
    private AccountService accountService;
    
    public ContextStartedEventListener(AccountService accountService) {
        this.accountService = accountService;
    }
    
    @Override
    public void onApplicationEvent(ContextStartedEvent event) {        
        logger.info("ContextStartedEvent received");
        
        
    }

}
